parameters:
    magice.user.already_logedin_redirect_target: /
    magice.user.class.form.registration: Magice\Bundle\UserBundle\Form\RegistrationType
    magice.user.class.form.info: Magice\Bundle\UserBundle\Form\UserInfoType
    magice.user.class.provider: Magice\Bundle\UserBundle\Model\UserProvider
    magice.user.class.manager: Magice\Bundle\UserBundle\Model\UserManager
    #magice.user.class.entity.user: ~
    #magice.user.class.entity.group: ~
    #magice.user.class.entity.info: ~
    magice.user.class.repository: Magice\Bundle\UserBundle\Model\UserRepository
    magice.user.class.responder.facebook: Magice\Bundle\UserBundle\OAuth\Response\Facebook

services:
    mg.user.repository:
        class: "%magice.user.class.repository%"
        factory_class: "%magice.user.class.repository%"
        factory_method: create
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "%magice.user.class.entity.user%"
            - "@service_container"

    mg.user.provider:
        class: "%magice.user.class.provider%"
        arguments:
            - "@mg.user.manager"
            - "@service_container"
            - "%magice.user.class.entity.info%"

    mg.user.manager:
        class: "%magice.user.class.manager%"
        public: false
        arguments:
            - "@security.encoder_factory"
            - "@fos_user.util.username_canonicalizer"
            - "@fos_user.util.email_canonicalizer"
            - "@fos_user.entity_manager"
            - "%fos_user.model.user.class%"

    mg.user.form.type.registration:
        class: "%magice.user.class.form.registration%"
        arguments:
            - "%fos_user.model.user.class%"
        tags:
            - { name: form.type, alias: mg_user_form_type_registration }

    mg.user.form.type.info:
        class:  "%magice.user.class.form.info%"
        tags:
            - { name: form.type, alias: mg_user_form_type_info }
