Magice\Bundle\UserBundle\Entity\UserInfo:
    properties:
        gender:
            - NotBlank:
                message: _mg.user.info.gender.blank

        firstname:
            - NotBlank:
                message: _mg.user.info.firstname.blank
            - Length:
                min: 4
                minMessage: _mg.user.info.firstname.short
                max: 255
                maxMessage: _mg.user.info.firstname.long

        lastname:
            - NotBlank:
                message: _mg.user.info.lastname.blank
            - Length:
                min: 3
                minMessage: _mg.user.info.lastname.short
                max: 255
                maxMessage: _mg.user.info.lastname.long

        birthday:
            - NotBlank:
                message: _mg.user.info.birthday.blank

        mobile:
            - NotBlank:
                message: _mg.user.info.mobile.blank
                groups: [Strict]
            - Magice\Validator\Constraints\Phone:
                defaultRegion: TH
                message: _mg.user.info.mobile.invalid

        telHome:
            - Magice\Validator\Constraints\Phone:
                defaultRegion: TH
                message: _mg.user.info.tel_home.invalid

        telWork:
            - Magice\Validator\Constraints\Phone:
                defaultRegion: TH
                message: _mg.user.info.tel_work.invalid
