FOS\UserBundle\Model\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: usernameCanonical
            errorPath: username
            message: _mg.user.username.already_used
            groups: [Register, Profile]
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: emailCanonical
            errorPath: email
            message: _mg.user.email.already_used
            groups: [Register, Profile]

    properties:
        username:
            - Magice\Validator\Constraints\Username:
                reservedWords: "admin,staff,joyprice,support"
                min: 3
                max: 20
                groups: [Register, Profile]
            - NotBlank:
                message: _mg.user.username.blank
                groups: [Register, Profile]
            - Length:
                min: 3
                minMessage: _mg.user.username.short
                max: 20
                maxMessage: _mg.user.username.long
                groups: [Register, Profile]

        email:
            - NotBlank:
                message: _mg.user.email.blank
                groups: [Register, Profile]
            - Length:
                min: 2
                minMessage: _mg.user.email.short
                max: 254
                maxMessage: _mg.user.email.long
                groups: [Register, Profile]
            - Email:
                message: _mg.user.email.invalid
                groups: [Register, Profile]

        plainPassword:
            - Magice\Validator\Constraints\Password:
                min: 4
                max: 4096
                message: _mg.user.password.invalid
                groups: [Register, ResetPassword, ChangePassword]
            - NotBlank:
                message: _mg.user.password.blank
                groups: [Register, ResetPassword, ChangePassword]
            - Length:
                min: 4
                max: 4096
                minMessage: _mg.user.password.short
                groups: [Register, Profile, ResetPassword, ChangePassword]

FOS\UserBundle\Model\Group:
    properties:
        name:
            - NotBlank:
                message: _mg.user.group.blank
                groups: [Register]
            - Length:
                min: 2
                minMessage: _mg.user.group.short
                max: 255
                maxMessage: _mg.user.group.long
                groups: [Register]

Magice\Bundle\UserBundle\Entity\UserInfo:
    properties:
        gender:
            - NotBlank:
                message: _mg.user.info.gender.blank

        firstname:
            - NotBlank:
                message: _mg.user.info.firstname.blank
            - Length:
                min: 4
                minMessage: _mg.user.info.firstname.short
                max: 255
                maxMessage: _mg.user.info.firstname.long

        lastname:
            - NotBlank:
                message: _mg.user.info.lastname.blank
            - Length:
                min: 3
                minMessage: _mg.user.info.lastname.short
                max: 255
                maxMessage: _mg.user.info.lastname.long

        birthday:
            - NotBlank:
                message: _mg.user.info.birthday.blank

        mobile:
            - NotBlank:
                message: _mg.user.info.mobile.blank
                groups: [Strict]
            - Magice\Validator\Constraints\Phone:
                defaultRegion: TH
                message: _mg.user.info.mobile.invalid

        telHome:
            - Magice\Validator\Constraints\Phone:
                defaultRegion: TH
                message: _mg.user.info.tel_home.invalid

        telWork:
            - Magice\Validator\Constraints\Phone:
                defaultRegion: TH
                message: _mg.user.info.tel_work.invalid
