Magice\Bundle\UserBundle\Entity\UserInfo:
    properties:
        gender:
            - NotBlank:
                message: _mg.user.info.gender.blank

        firstname:
            - NotBlank:
                message: _mg.user.info.firstname.blank
            - Length:
                min: 4
                minMessage: _mg.user.info.firstname.short
                max: 255
                maxMessage: _mg.user.info.firstname.long

        lastname:
            - NotBlank:
                message: _mg.user.info.lastname.blank
            - Length:
                min: 3
                minMessage: _mg.user.info.lastname.short
                max: 255
                maxMessage: _mg.user.info.lastname.long
